version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-front
    ports:
      - '5555:5555'
    volumes:
      - .:/app
      - /app/node_modules