import "./globals.css";
import { montserrat } from "./libs/fonts";

export const metadata = {
  title: "Vive la UCA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${montserrat.className} antialiased`}>{children}</body>
    </html>
  );
}
